CarmenMariaMP/UStudy

- app/templates/cursosdisponibles.html
- app/views.py
- ustudy/urls.py
Implementada la vista de cursos disponibles
> frontend: Template Cursos Disponibles

- .github/workflows/codacy-analisys.yaml
- .github/workflows/codacy.yaml
- .github/workflows/heroku.yaml
- .github/workflows/tests.yaml
3 workflows para tests, codacy y heroku
> ci:creacion del workflow inicial

- .github/workflows/codacy.yaml
- .github/workflows/heroku.yaml
- .github/workflows/tests.yaml
errores en la sintaxis del fichero
> ci: solucion errores del workflow heroku

- Initial_population/Scraping_asignaturas_json.py
- Initial_population/guia_asignaturas_populate.txt
- datos_populate_asignatura.json
Se ha realizado un script de scrapping para sacar las asignaturas de las titulaciones de la universidad de Sevilla y su posterior transformación a JSON para realizar el populate inicial (mirar guía).
> backend: Populate inicial de 638 asignaturas

- app/templates/login.html
Añadida validación vista login.html #51
> frontend: Validacion vista login.html

- app/templates/cursosdisponibles.html
- app/views.py
- ustudy/urls.py
Implementación para suscribirse a un curso. Cambiado boton por enlace con aspecto de boton para facilitar la petición
> backend: Suscripcion a un curso

- app/templates/curso.html
- app/templates/cursosdisponibles.html
- app/templates/inicio.html
- app/templates/login.html
- app/templates/miscursos.html
Se ocultan algunos botones que no tienen funcionalidad actualmente.
> frontend: Cambio botones

- app/templates/cursosdisponibles.html
- app/templates/pasarela_pago.html
implementada la primera version de la vista de los pagos
> frontend: vista metodos de pago

- app/static/css/valoraciones.css
- app/templates/curso.html
- app/templates/cursosdisponibles.html
- app/templates/inicio_profesor.html
- app/templates/miscursos.html
Se añaden los GET y los POST de valoraciones en frontend
> frontend: Valoraciones

- .github/workflows/tests.yaml
ahora ejecutan los tests de modelo
> ci: faltaba salto de linea

- app/forms.py
Cuando se realizaba un migrate con la una base de datos recién creada saltaba un error.
"no existe la relación «app_asignatura»".
> Fix: Query registro

- .github/workflows/tests.yaml
ahora ejecutan los tests de modelo
> ci: carga de la base de datos

- app/views.py
Se añade la paginación y la lógica que necesitaba el controlador para que funcione el listado de "miscursos"
> backend: Arreglo de miscursos

- Initial_population/Scraping_asignaturas_json.py
- app/forms.py
- app/models.py
- app/static/js/valoraciones.js
- app/views.py
- ustudy/settings.py
- ustudy/urls.py
> devops: arreglados algunos malos olores

- app/admin.py
- app/apps.py
- app/forms.py
- app/static/css/valoraciones.css
- app/tests/selenium.py
- app/tests/tests_models.py
- app/views.py
Eliminado unos cuantos de malos olores
> Eliminado malos olores

- .github/workflows/tests.yaml
- requirements.txt
> ci: cambio de version de postgres

- app/tests/tests_models.py
- app/views.py
Se quita los imports que no se utilizaban, se añade un import que faltaba y se quita un printeo en los tests de los modelos.
> backend: Ajuste en views.py

- app/forms.py
- app/static/css/archivo.css
- app/templates/archivo.html
Se mejora la visualización de lo comentarios.
> frontend: Visualización comentarios

- app/templates/cursosdisponibles.html
- app/views.py
Al suscribirse a un curso, te redirecciona al curso correspondiente, cambiando el path para evitar problemas.
> fix: Suscripción

- app/tests/tests_forms.py
Con la adición de los campos gdpr en el registro, algunos tests dan problemas. Han sido solucionados
> Fix: Tests arreglados

- app/templates/error.html
- app/templates/informacion_transferencia.html
- app/templates/perfil.html
- app/templates/registro.html
Se han realizado las siguientes mejoras de la auditoría de calidad : 01,04,09,010
> frontend: Mejoras auditoría S3

- app/tests/tests_views.py
- app/views.py
Para la rentabilidad del proyecto se ha realizado una intercambio monetario de 8-12
> Fix: Intercambio monetario

- app/templates/privacidad.html
- app/templates/sobre_nosotros.html
- app/templates/terminos.html
Quitado cabeceras de privacidad,sobre nosotros y politicas
> Quitado cabeceras de privacidad,sobre nosotros y politicas

- app/templates/cursosdisponibles.html
- app/views.py
- ustudy/urls.py
Implementado buscar curso en cursos disponibles
> Implementado buscador cursos

- app/templates/cursosdisponibles.html
- app/templates/inicio_profesor.html
- app/templates/terminos.html
- app/views.py
Se arregla la vista del buscador de cursos y la vista de los cursos del "inicio_profesor.html" y "cursosdisponibles.html"
> frontend: Arreglo buscador
